server:
  port: 29001

cloud:
  grpc:
    server:
      port: 23001

spring:
  application:
    name: zookeeper-grpc-server-example
  cloud:
    zookeeper:
      discovery:
        register: true
        root: /spring-cloud-grpc-registry/services
      connect-string: 127.0.0.1:2181

#opentracing:
#  jaeger:
#    enable: true
#    http-sender:
#      url: http://127.0.0.1:14268/api/traces
#    log-spans: true
