server:
  port: 9001

cloud:
  grpc:
    server:
      port: 13001

spring:
  application:
    name: nacos-grpc-server-example
  cloud:
    nacos:
      discovery:
        register-enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 098988d8-24b0-4ffe-bcc1-1e30c9d99b62
